# Generated by Django 6.0 on 2026-02-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_product_name_alter_product_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homepage/follow/')),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=200)),
                ('hero_description', models.TextField()),
                ('hero_image', models.ImageField(upload_to='homepage/')),
                ('hero_mini_image', models.ImageField(upload_to='homepage/')),
                ('products_title', models.CharField(max_length=200)),
                ('products_subtitle', models.TextField()),
                ('ingredients_title', models.CharField(max_length=200)),
                ('ingredients_subtitle', models.TextField()),
                ('feature_title', models.TextField()),
                ('feature_discount_text', models.CharField(max_length=50)),
                ('feature_image', models.ImageField(upload_to='homepage/')),
                ('feature_description', models.TextField()),
                ('ingredient_hero_title', models.CharField(max_length=200)),
                ('ingredient_hero_description', models.TextField()),
                ('ingredient_hero_image', models.ImageField(upload_to='homepage/')),
                ('stat_customers', models.CharField(max_length=20)),
                ('stat_products', models.CharField(max_length=20)),
                ('follow_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='homepage/ingredients/')),
            ],
        ),
    ]
