# Generated by Django 6.0 on 2026-02-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_followgallery_homepage_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('paragraph_1', models.TextField()),
                ('paragraph_2', models.TextField()),
                ('paragraph_3', models.TextField()),
                ('button_text', models.CharField(default='Explore Our Products', max_length=100)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='about/')),
            ],
        ),
    ]
