# Generated by Django 6.0 on 2026-02-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='is_whatsapp_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='whatsapp_message',
            field=models.TextField(blank=True, default='Hello Daania Beauty, I have a question about your product.'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Enter number with country code without + (Example: 919876543210)', max_length=20, null=True),
        ),
    ]
